### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by chewrocca** [datadrivers/terraform-provider-nexus#171]
**Describe the bug**
The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call.

This is after upgrading the provider to 1.16.0.

**To Reproduce**
ran `terraform plan` and then during `terraform apply` it fails with things such as the following;

```sh
Error: could not create blobstore "pxblob": HTTP: 404, 404 page not found 

with module.nexus_repos_cph.nexus_blobstore_file.portworxblob,
   on modules/nexus-repos-proxy/main.tf line 15, in resource "nexus_blobstore_file" "portworxblob":
   15: resource "nexus_blobstore_file" "portworxblob" {
 
 Error: Plugin did not respond
 
 with module.nexus_repos_bos.nexus_repository.adobe,
   on modules/nexus-repos-proxy/main.tf line 27, in resource "nexus_repository" "adobe":
   27: resource "nexus_repository" "adobe" {
 
The plugin encountered an error, and failed to respond to the
plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
contain more details.
```

```sh
│ Error: Request cancelled
│ 
│   with module.nexus_repos_aus.nexus_repository.adobe,
│   on modules/nexus-repos-proxy/main.tf line 27, in resource "nexus_repository" "adobe":
│   27: resource "nexus_repository" "adobe" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.

│ Error: Request cancelled
│ 
│   with module.nexus_repos_aus.nexus_repository.apache-snapshots,
│   on modules/nexus-repos-proxy/main.tf line 61, in resource "nexus_repository" "apache-snapshots":
│   61: resource "nexus_repository" "apache-snapshots" {
│ 
│ The plugin.(*GRPCProvider).ValidateResourceConfig request was cancelled.
```

**Additional Info**

```sh
Stack trace from the terraform-provider-nexus_v1.16.0 plugin:

panic: interface conversion: interface {} is bool, not *bool

goroutine 333 [running]:
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.getRepositoryFromResourceData(0x0)
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:604 +0x1ef7
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.resourceRepositoryCreate(0x0, {0xaaf380, 0xc000424d20})
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:983 +0x66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xb07100, {0xcdc318, 0xc0000ad500}, 0x2, {0xaaf380, 0xc000424d20})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002e70a0, {0xcdc318, 0xc0000ad500}, 0xc00055f450, 0xc00059c980, {0xaaf380, 0xc000424d20})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000d2d8, {0xcdc318, 0xc0000ad500}, 0xc00079d450)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00016ce00, {0xcdc3c0, 0xc0000aa9f0}, 0xc00014e070)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbae2c0, 0xc00016ce00}, {0xcdc3c0, 0xc0000aa9f0}, 0xc00009de00, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000274a80, {0xceaf38, 0xc0001ee480}, 0xc000631680, 0xc0002ffa10, 0x11ae340, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000274a80, {0xceaf38, 0xc0001ee480}, 0xc000631680, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x294
panic: interface conversion: interface {} is bool, not *bool

goroutine 507 [running]:
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.getRepositoryFromResourceData(0x0)
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:604 +0x1ef7
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.resourceRepositoryCreate(0x0, {0xaaf380, 0xc0005cdf80})
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:983 +0x66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xb07100, {0xcdc318, 0xc000424580}, 0x2, {0xaaf380, 0xc0005cdf80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0002c2b60, {0xcdc318, 0xc000424580}, 0xc000306ea0, 0xc0002eb780, {0xaaf380, 0xc0005cdf80})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c0a8, {0xcdc318, 0xc000424580}, 0xc00035ed20)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000238780, {0xcdc3c0, 0xc00051adb0}, 0xc0000fc070)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbae2c0, 0xc000238780}, {0xcdc3c0, 0xc00051adb0}, 0xc000322060, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000250700, {0xceaf38, 0xc00019e180}, 0xc0006a97a0, 0xc000308090, 0x11ae340, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000250700, {0xceaf38, 0xc00019e180}, 0xc0006a97a0, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x294
panic: interface conversion: interface {} is bool, not *bool

goroutine 459 [running]:
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.getRepositoryFromResourceData(0x0)
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:604 +0x1ef7
github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated.resourceRepositoryCreate(0x0, {0xaaf380, 0xc000399650})
	github.com/datadrivers/terraform-provider-nexus/internal/services/deprecated/resource_repository.go:983 +0x66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xb07100, {0xcdc318, 0xc000012480}, 0x2, {0xaaf380, 0xc000399650})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00031cb60, {0xcdc318, 0xc000012480}, 0xc000459ad0, 0xc0003ff300, {0xaaf380, 0xc000399650})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00000c0a8, {0xcdc318, 0xc000012480}, 0xc000636370)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000190b80, {0xcdc3c0, 0xc0004cf3e0}, 0xc0000b2070)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbae2c0, 0xc000190b80}, {0xcdc3c0, 0xc0004cf3e0}, 0xc000650180, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002a2700, {0xceaf38, 0xc000216480}, 0xc00066aa20, 0xc0002bd680, 0x11ae340, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1297 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002a2700, {0xceaf38, 0xc000216480}, 0xc00066aa20, 0x0)
	google.golang.org/grpc@v1.40.0/server.go:1626 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.40.0/server.go:941 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.40.0/server.go:939 +0x294

Error: The terraform-provider-nexus_v1.16.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

script returned exit code 1
```

**Comment by anmoel** [comment]
Hi @chewrocca,

thanks for your report.
I found the error and it should be fixed in version 1.16.1
please check this and reopen the ticket if it still exists.

regards 
André
