### ISSUE TITLE
Error: Plugin did not respond

### ISSUE THREAD

**Issue by abondoe** [datadrivers/terraform-provider-nexus#208]
**Describe the bug**
I'm trying to change the password of a user.

**To Reproduce**
1. I'm using plugin 1.18.0
```
provider "nexus" {
  insecure = false
  password = "xxx"
  url      = "https://xxx"
  username = "admin"
}
```
2. With Sonatype Nexus 3.38.0-01
3. I've imported the admin user, and trying to change the password
```
resource "nexus_security_user" "admin" {
  userid    = "admin"
  password  = "new-password"

  depends_on = [
    aws_lb_listener_rule.redirect_http_to_https,
    aws_alb_listener.https
  ]
}
```
4. The password gets changed but apply ends with an error
5. See error
```
nexus_security_user.admin: Modifying... [id=admin]
╷
│ Error: Plugin did not respond
│ 
│   with nexus_security_user.admin,
│   on config.tf line 1, in resource "nexus_security_user" "admin":
│    1: resource "nexus_security_user" "admin" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-nexus_v1.18.0 plugin:
panic: Invalid diagnostic: empty summary. This is always a bug in the provider implementation
goroutine 16 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.DiagsToProto({0xc00026e340, 0x1, 0xc0006ed7d0})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:72 +0x2b3
github.com/hashicorp/terraform-plugin-sdk/v2/internal/plugin/convert.AppendProtoDiag({0x0, 0x0, 0x0}, {0xb1aee0, 0xc00074c750})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/internal/plugin/convert/diagnostics.go:25 +0x99
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0001180a8, {0xcf9fd8, 0xc000125d00}, 0xc0000917c0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:978 +0xdcb
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc000128780, {0xcfa080, 0xc000472990}, 0xc0006cbd50)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbc7de0, 0xc000128780}, {0xcfa080, 0xc000472990}, 0xc00007f080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000142700, {0xd08cf8, 0xc0000e7ba0}, 0xc0004ed0e0, 0xc0003a04e0, 0x11d7600, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc000142700, {0xd08cf8, 0xc0000e7ba0}, 0xc0004ed0e0, 0x0)
	google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.43.0/server.go:919 +0x294
Error: The terraform-provider-nexus_v1.18.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**
Apply finishes without any errors

**Comment by anmoel** [comment]
Hi @abondoe,

thanks for your response. we will test your szenario with our provider and the new nexus version.
