### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by mirisu2** [datadrivers/terraform-provider-nexus#212]
**Describe the bug**
I'm trying to create nexus_repository_apt_proxy resource. But it fail.

**To Reproduce**
```
$ terraform version
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/datadrivers/nexus v1.18.0

resource "nexus_repository_apt_proxy" "repository" {
  distribution = "focal"
  flat         = false
  name         = "focal"
  proxy {
    remote_url       = "http://archive.ubuntu.com/ubuntu"
    content_max_age  = 10080
    metadata_max_age = 10080
  }
  storage {
    blob_store_name                = "default"
    strict_content_type_validation = true
  }

  online = true
  negative_cache {
    enabled = true
    ttl     = 1440
  }
}

$ terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # nexus_repository_apt_proxy.repository will be created
  + resource "nexus_repository_apt_proxy" "repository" {
      + distribution = "focal"
      + flat         = false
      + id           = (known after apply)
      + name         = "focal"
      + online       = true

      + negative_cache {
          + enabled = true
          + ttl     = 1440
        }

      + proxy {
          + content_max_age  = 10080
          + metadata_max_age = 10080
          + remote_url       = "http://archive.ubuntu.com/ubuntu"
        }

      + storage {
          + blob_store_name                = "default"
          + strict_content_type_validation = true
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

nexus_repository_apt_proxy.repository: Creating...
╷
│ Error: Request cancelled
│ 
│   with nexus_repository_apt_proxy.repository,
│   on main.tf line 11, in resource "nexus_repository_apt_proxy" "repository":
│   11: resource "nexus_repository_apt_proxy" "repository" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-nexus_v1.18.0 plugin:

panic: runtime error: index out of range [0] with length 0

goroutine 38 [running]:
github.com/datadrivers/terraform-provider-nexus/internal/services/repository.getAptProxyRepositoryFromResourceData(0x0)
        github.com/datadrivers/terraform-provider-nexus/internal/services/repository/resource_repository_apt_proxy.go:53 +0x10de
github.com/datadrivers/terraform-provider-nexus/internal/services/repository.resourceAptProxyRepositoryCreate(0x0, {0xac8680, 0xc0002190e0})
        github.com/datadrivers/terraform-provider-nexus/internal/services/repository/resource_repository_apt_proxy.go:175 +0x66
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xb20a00, {0xcf9fd8, 0xc000562540}, 0x2, {0xac8680, 0xc0002190e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:329 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0004696c0, {0xcf9fd8, 0xc000562540}, 0xc0000aadd0, 0xc000095380, {0xac8680, 0xc0002190e0})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/resource.go:467 +0x871
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0002c4090, {0xcf9fd8, 0xc000562540}, 0xc000090410)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.10.1/helper/schema/grpc_provider.go:977 +0xd8a
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc0002c6700, {0xcfa080, 0xc00057e5d0}, 0xc00071a000)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/tf5server/server.go:603 +0x30e
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xbc7de0, 0xc0002c6700}, {0xcfa080, 0xc00057e5d0}, 0xc00070c300, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.5.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002e2700, {0xd08cf8, 0xc00024f6c0}, 0xc0004f4000, 0xc0004d0030, 0x11d7600, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1282 +0xccf
google.golang.org/grpc.(*Server).handleStream(0xc0002e2700, {0xd08cf8, 0xc00024f6c0}, 0xc0004f4000, 0x0)
        google.golang.org/grpc@v1.43.0/server.go:1616 +0xa2a
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.43.0/server.go:921 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.43.0/server.go:919 +0x294

Error: The terraform-provider-nexus_v1.18.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Expected behavior**
I expected a resource is created.

**Comment by mirisu2** [comment]
It is strange behavior, but if I add **optional** param `http_client {}` into `nexus_repository_apt_proxy` block - I have success

**Comment by SebastianJ91** [comment]
The same happens for me on nexus_repository_docker_proxy ressource.

**Comment by anmoel** [comment]
hi,

thanks for your PR. We will fix the issue in next time. the http_client should be optional for all proxies.
