### ISSUE TITLE
Error: Plugin did not respond - panic: runtime error: index out of range [0] with length | by adding Repos

### ISSUE THREAD

**Issue by torsten-online** [datadrivers/terraform-provider-nexus#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.6.5

### Nexus Provider Version

1.22.0

### Nexus  Version

3.62.0

### Affected Resource(s)/Data Source(s)

nexus_repository_maven_proxy

### Terraform Configuration Files

```HCL
# Maven Proxy Repositories
resource "nexus_repository_maven_proxy" "maven_proxy" {
  for_each = { for repo in var.maven_proxy_repos : repo.name => repo }

  name   = each.value.name
  online = true

  maven {
    version_policy = each.value.version_policy
    layout_policy  = each.value.layout_policy
  }

  proxy {
    remote_url = each.value.remote_url
  }

  http_client {
    auto_block = false # Set this to true or false as required
    blocked    = false # Set this to true or false as required
  }

  storage {
    blob_store_name                = "default" # Replace with your blob store name
    strict_content_type_validation = true      # Set to true or false as required
  }
}
```

### Debug Output/Panic Output

```shell
module.nexus_repositories.nexus_repository_maven_proxy.maven_proxy["maven-proxy"]: Creating...
2023-12-04T05:32:33.430+0100 [INFO]  Starting apply for module.nexus_repositories.nexus_repository_maven_proxy.maven_proxy["maven-proxy"]
2023-12-04T05:32:33.430+0100 [INFO]  Starting apply for module.nexus_repositories.nexus_repository_yum_proxy.yum_proxy["yum-proxy"]
2023-12-04T05:32:33.430+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: setting computed for "component" from ComputedKeys: timestamp="2023-12-04T05:32:33.430+0100"
2023-12-04T05:32:33.430+0100 [DEBUG] module.nexus_repositories.nexus_repository_yum_proxy.yum_proxy["yum-proxy"]: applying the planned Create change
2023-12-04T05:32:33.430+0100 [DEBUG] module.nexus_repositories.nexus_repository_maven_proxy.maven_proxy["maven-proxy"]: applying the planned Create change
2023-12-04T05:32:33.431+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: setting computed for "http_client.0.connection" from ComputedKeys: timestamp="2023-12-04T05:32:33.431+0100"
2023-12-04T05:32:33.431+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: setting computed for "http_client.0.connection" from ComputedKeys: timestamp="2023-12-04T05:32:33.431+0100"
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: panic: runtime error: index out of range [0] with length 0
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: goroutine 85 [running]:
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/datadrivers/terraform-provider-nexus/internal/services/repository.getNpmProxyRepositoryFromResourceData(0xe36cf0?)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/datadrivers/terraform-provider-nexus/internal/services/repository/resource_repository_npm_proxy.go:56 +0xdcf
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/datadrivers/terraform-provider-nexus/internal/services/repository.resourceNpmProxyRepositoryCreate(0x0?, {0xbb0a00?, 0xc0000b8960})
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/datadrivers/terraform-provider-nexus/internal/services/repository/resource_repository_npm_proxy.go:167 +0x5a
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xe30598?, {0xe30598?, 0xc00041cd50?}, 0xd?, {0xbb0a00?, 0xc0000b8960?})
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:766 +0x163
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000487420, {0xe30598, 0xc00041cd50}, 0xc000725860, 0xc000431180, {0xbb0a00, 0xc0000b8960})
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:909 +0xa7e
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc0003bbb30, {0xe30598?, 0xc00041cc60?}, 0xc000814320)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xdbc
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00026adc0, {0xe30598?, 0xc00041c3f0?}, 0xc00025e1c0)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x56a
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xcd4ca0?, 0xc00026adc0}, {0xe30598, 0xc00041c3f0}, 0xc00025e070, 0x0)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x169
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: google.golang.org/grpc.(*Server).processUnaryRPC(0xc00025c1e0, {0xe344f8, 0xc00051a820}, 0xc00032e000, 0xc00049a030, 0x136ba18, 0x0)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         google.golang.org/grpc@v1.57.0/server.go:1360 +0xe15
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: google.golang.org/grpc.(*Server).handleStream(0xc00025c1e0, {0xe344f8, 0xc00051a820}, 0xc00032e000, 0x0)
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         google.golang.org/grpc@v1.57.0/server.go:1737 +0x9e7
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         google.golang.org/grpc@v1.57.0/server.go:982 +0x8d
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0: created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 66
2023-12-04T05:32:33.434+0100 [DEBUG] provider.terraform-provider-nexus_v1.22.0:         google.golang.org/grpc@v1.57.0/server.go:980 +0x165
2023-12-04T05:32:33.435+0100 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/datadrivers/nexus/1.22.0/linux_amd64/terraform-provider-nexus_v1.22.0 pid=1976 error="exit status 2"
2023-12-04T05:32:33.435+0100 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-04T05:32:33.435+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-04T05:32:33.435+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-04T05:32:33.435+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-04T05:32:33.435+0100 [ERROR] plugin.(*GRPCProvider).ApplyResourceChange: error="rpc error: code = Unavailable desc = error reading from server: EOF"
2023-12-04T05:32:33.440+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-12-04T05:32:33.440+0100 [ERROR] vertex "module.nexus_repositories.nexus_repository_maven_proxy.maven_proxy[\"maven-proxy\"]" error: Plugin did not respond
2023-12-04T05:32:33.445+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-12-04T05:32:33.445+0100 [ERROR] vertex "module.nexus_repositories.nexus_repository_npm_proxy.npm_proxy[\"npm-proxy\"]" error: Plugin did not respond
2023-12-04T05:32:33.450+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-12-04T05:32:33.450+0100 [ERROR] vertex "module.nexus_repositories.nexus_repository_maven_hosted.maven_hosted[\"maven-hosted\"]" error: Plugin did not respond
2023-12-04T05:32:33.455+0100 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2023-12-04T05:32:33.455+0100 [ERROR] vertex "module.nexus_repositories.nexus_repository_yum_proxy.yum_proxy[\"yum-proxy\"]" error: Plugin did not respond
╷
│ Error: Plugin did not respond
│ 
│   with module.nexus_repositories.nexus_repository_maven_proxy.maven_proxy["maven-proxy"],
│   on ../module/repos.tf line 2, in resource "nexus_repository_maven_proxy" "maven_proxy":
│    2: resource "nexus_repository_maven_proxy" "maven_proxy" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵
```

### Expected Behaviour

I want create more than one (for example) Maven Proxy Repo (and more) over my own Terraform Module for Nexus.

This happens every time, when more then one repo is created.

### Actual Behaviour

Terraform quits with the "Provider issue": panic: runtime error: index out of range [0] with length

Error can be fixed - but maybe there is an major issue, e.g. by missing documentation ? 

I added negative_cache example from here: [negative_cache_maven_proxy](https://github.com/datadrivers/terraform-provider-nexus/blob/main/examples/resources/nexus_repository_maven_proxy/resource.tf#L16C1-L19C4])

and this fixed my major issue! I think the issue happen because of usage for_each in my code and the parameter negative_cache is required to be set.

Is there maybe an issue with the documentation? I dont find any hints about this. Thanks

### Steps to Reproduce

A terraform apply with my sample code of my module should show the issue.

It can be fixed, by adding 

`````
negative_cache {
    enabled = true
    ttl     = 1440
  }
``````
To all repo resources, which have this required parameter.

### References

#352 
#212

**Comment by anmoel** [comment]
@torsten-online hello

thanks for sending of the issue. 
that's a documentation error. the negative_cache  block is required.
we will fix the documentation in the next release

**Comment by anmoel** [comment]
we discussed internally, that we will follow the sonatype Nexus API. 
so we make the block negative_cache and it's fields as required 
https://github.com/datadrivers/terraform-provider-nexus/releases/tag/v2.4.0
