### ISSUE TITLE
terraform plan fails

### ISSUE THREAD

**Issue by I-Would-Like-To-Report-A-Bug-Please** [datadrivers/terraform-provider-nexus#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.0.11

### Nexus Provider Version

2.5.0

### Nexus  Version

3.70.2-01

### Affected Resource(s)/Data Source(s)

3.70.2-01

### Terraform Configuration Files

```HCL
terraform {
  required_providers {
    nexus = {
      source  = "datadrivers/nexus"
      version = "2.5.0"
    }
  }
}

resource "nexus_blobstore_group" "it-releases" {
  fill_policy = "writeToFirst"
  members     = [
    nexus_blobstore_s3.s3_it_releases.name,
  ]
  name        = "it-releases"
}
```

### Debug Output/Panic Output

```shell
nexus_blobstore_group.it-releases: Refreshing state... [id=it-releases]
╷
│ Error: Plugin did not respond
│ 
│   with nexus_blobstore_group.it-releases,
│   on nexus_blobstore.tf line 9, in resource "nexus_blobstore_group" "it-releases":
│    9: resource "nexus_blobstore_group" "it-releases" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵
╷
╷
│ Error: Request cancelled
│ 
│   with nexus_repository_maven_group.pp-maven2,
│   on nexus_repository.tf line 181, in resource "nexus_repository_maven_group" "pp-maven2":
│  181: resource "nexus_repository_maven_group" "pp-maven2" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵

...
<bunch of plugin did not respond or request cancelled errors for multiple repositories>
...
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-nexus_v2.5.0 plugin:

panic: Error reading level state: strconv.ParseInt: parsing "9223372036854776000": value out of range

goroutine 1044 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).get(0xc000598380, {0xc000841210, 0x1, 0x1}, 0x8?)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:556 +0x319
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).State(0xc000598380)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource_data.go:354 +0x473
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).ShimInstanceStateFromValue(0xc0003afb20, {{{0xe8c038?, 0xc00009c050?}}, {0xc4d420?, 0xc00028f110?}})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/resource.go:698 +0x1d8
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc00039e8b8, {0xe8c070?, 0xc00028eb10?}, 0xc000616240)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.34.0/helper/schema/grpc_provider.go:682 +0x41d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc000251180, {0xe8c070?, 0xc00028e270?}, 0xc000aa8000)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/tf5server/server.go:783 +0x309
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0xd29920, 0xc000251180}, {0xe8c070, 0xc00028e270}, 0xc000598000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:482 +0x1a6
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001a6e00, {0xe8c070, 0xc00028e1e0}, {0xe90a60, 0xc000488000}, 0xc0001e6000, 0xc0003b9620, 0x1416f88, 0x0)
        google.golang.org/grpc@v1.66.0/server.go:1393 +0xe1a
google.golang.org/grpc.(*Server).handleStream(0xc0001a6e00, {0xe90a60, 0xc000488000}, 0xc0001e6000)
        google.golang.org/grpc@v1.66.0/server.go:1804 +0xe8b
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.66.0/server.go:1029 +0x8b
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 8
        google.golang.org/grpc@v1.66.0/server.go:1040 +0x125

Error: The terraform-provider-nexus_v2.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

### Expected Behaviour

Terraform plan should work and not crash

### Actual Behaviour

Plugin crashed

### Steps to Reproduce

`terraform plan`

But I'm not sure what's specific about this blob store group that causes panic. Our repositories are quite huge, so maybe it's something related to size?

**Comment by chris-ruecker** [comment]
Hi, do you happen to run a 32 bit version of Terraform? If yes, could you try a 64bit version?

With the error message, i came across this issue here which contains an explanation of why this happens:
https://github.com/hashicorp/terraform-provider-google/issues/6518

**Comment by xgcssch** [comment]
Hi!
Same problem for me.
I'm using the Docker image `hashicorp/terraform:1.9` on an 64Bit machine:
```
Terraform v1.9.8
on linux_amd64
+ provider registry.terraform.io/datadrivers/nexus v2.5.0
```
Message is
```
panic: Error reading level state: strconv.ParseInt: parsing "9223372036854776000": value out of range
```
BTW: the integer IS larger then the maximum signed 64 bit Integer. Max `9,223,372,036,854,775,807` (inclusive)

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
For us it is single docker-compose one node installation.

Just checked Terraform:
``` bash
❯ terraform -version
Terraform v1.0.11
on linux_amd64

❯ file /var/lib/tfenv/versions/1.0.11/terraform 
/var/lib/tfenv/versions/1.0.11/terraform: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=oLZBNGHz70skNEAdhSHD/wzJydTaLhLbxOzYAwDlf/515RIPkbNiteahNWSa8i/XpyGuWV_TATduTbYzSf9, stripped
```

So definitely x64.

**Comment by xgcssch** [comment]
One more information:
If i recover the previous version of the `terraform.tfstate` the last change is as expected not seen by terraform, but there is also no crash anymore.
After removing and re-importing the changed resources the state is still valid. No crash.
Seems that the resulting state after a change is somehow corrupted.

**Comment by I-Would-Like-To-Report-A-Bug-Please** [comment]
https://github.com/datadrivers/terraform-provider-nexus/pull/582

Tested locally, and works fine now with the problematic blobstore.
